export const users_data = [
  {
    id: 1,
    img: 'https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
    username: 'Elva McDonald',
    email: 'elva@gmail.com',
    password: '$2a$10$T1koh5TYWB1dTWRDBGzSje6/jW3TcPXyMBg.yUpOy8isqPkXnQHPC',
    city: 'Nurabelen',
    country: 'ID',
    occupation: 'Computer Systems Analyst I',
    role: 'user',
    phone: '8346315874',
    isAdmin: false,
  },
  {
    id: 2,
    img: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Linnie Nelson',
    email: 'linnie@gmail.com',
    password: '$2a$10$qG1byiJAr4Z2GAGbgK2g7u9xjJXwEgbFNzRjD.8hTEKNZ5uW0g1dW',
    city: 'Zhanghekou',
    country: 'CN',
    occupation: 'Food Chemist',
    role: 'admin',
    phone: '9981906117',
    isAdmin: true,
  },
  {
    id: 3,
    img: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Brent Reeves',
    email: 'brent@gmail.com',
    password: '$2a$10$qcleBNKjPa3joi4Wk1QGeeI0X/51fDCbRjaeVr3lQTatYKDyy5AZm',
    city: 'Muang Sam Sip',
    country: 'TH',
    occupation: 'Staff Scientist',
    role: 'user',
    phone: '3868813669',
    isAdmin: false,
  },
  {
    id: 4,
    img: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Adeline Watson',
    email: 'adeline@gmail.com',
    password: '$2a$10$GkONwg6PHOD2qVJ79NE0e.r42n1.vO7Uy.gxjKH6i6Migq6imdkB2',
    city: 'San Luis',
    country: 'AR',
    occupation: 'Associate Professor',
    role: 'user',
    phone: '8535391908',
    isAdmin: false,
  },
  {
    id: 5,
    img: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Juan Harrington',
    email: 'juan@gmail.com',
    password: '$2a$10$G4vsny7/KB6AvF0ekkRYFO6L1KJ1GKTXV/HznAzj0aiBhMgpQ.6ce',
    city: 'Osieck',
    country: 'PL',
    occupation: 'Senior Cost Accountant',
    role: 'superadmin',
    phone: '5367727534',
    isAdmin: true,
  },
  {
    id: 6,
    img: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Augusta McGee',
    email: 'augusta@gmail.com',
    password: '$2a$10$s0XODMBmWZtyf8AdkIt7qe.yVeqbsKsDmM2WAD91Mz7dksptDRw76',
    city: 'São Jerônimo',
    country: 'BR',
    occupation: 'Chemical Engineer',
    role: 'admin',
    phone: '8601650433',
    isAdmin: true,
  },
  {
    id: 7,
    img: 'https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600',
    username: 'Angel Thomas',
    email: 'angel@gmail.com',
    password: '$2a$10$ows/ORtS4gOAUBcULhWOEu2hOvLiscax3236rrQe4orQBJY56bRn6',
    city: 'Hanjiashu',
    country: 'CN',
    occupation: 'Quality Engineer',
    role: 'superadmin',
    phone: '3096621613',
    isAdmin: true,
  },
];
